### PR TITLE
feat: add new theme

### PR DESCRIPTION
**Pull request by dianalin2**

### CODE REVIEW

**Comment by DarinMao** [comment]
can you use fontsource instead?

**Comment by DarinMao** [comment]
I think link needs a hover style at least?

**Comment by DarinMao** [comment]
regarding recaptcha not changing color

we could just do [this](https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed) and put the recaptcha notice elsewhere

we could also just not care because nobody changes color theme like that usually

**Comment by dianalin2** [comment]
> regarding recaptcha not changing color
> 
> we could just do [this](https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed) and put the recaptcha notice elsewhere
> 
> we could also just not care because nobody changes color theme like that usually

I think we can just ignore

**Comment by DarinMao** [comment]
seems fine to me

**Review by DarinMao — APPROVED** [review]

**Pull request merged**
